---
title: "映像と効果音の印象評価"
author: "神戸大学正田研究室"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych/css/jspsych-mk.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(htmltools)
tagList(
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/jspsych.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-instructions.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-survey-html-form.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-survey-multi-select.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-html-button-response.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-survey-likert.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-audio-button-response.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-video-button-response.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-video-slider-response.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-audio-keyboard-response.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-video-keyboard-response.js'),
tags$script(src='https://shodalab.github.io/jsPsychSheet/jspsych/plugins/jspsych-survey-text-mk.js'),
)
```

```{js}
const timeline = [];

///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
var ic1 = {
    type: 'survey-html-form',
    preamble: '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%; margin-left:10%;margin-right:10%;">'+
              '<p><h1>音と映像の印象評価実験</h1></p></div>',
    html: '<div style = "font-size: 18px; line-height:1.8em; text-align: left; width: 80%; margin-left:10%;margin-right:10%;">'+
          '<p>このたびは神戸大学国際人間科学部グローバル文化学科正田研究室によるWeb実験にご協力いただきありがとうございます。実験の前に下記の項目をご確認ください。</p>'+
          '<ul style = "text-align:center; display:inline-block; line-height:2em;">' +
          '<li style = "text-align:left">実験は，人によりますが概ね40分程度かかります。途中でやめると最初からやり直しになってしまいます。余裕のあるときに行ってください。</li>'+
          '<li style = "text-align:left">この実験では音と映像を使用します。実験の前に映像が流れるかの確認をしますので，映像および音声が流れるかご確認ください。</li>'+
          '<li style = "text-align:left">可能な限りパソコンからご参加ください。Windowsの方はFirefox，Macの方はSafariが推奨環境です。<b>Google Chromeでは動作しません</b>のでご注意ください。</li>'+
          '<li style = "text-align:left">実験の途中でブラウザを閉じてしまうと最初からやり直しになってしまいます。実験の途中でブラウザを閉じないでください。</li>'+
          '<li style = "text-align:left">授業で参加されている方は，<b>実験の最後に表示される記号を写真で撮る等，保存しておいてください</b>。</li></ul>'+
          '<p>実験は下記の手順で行います。</p>' +
          '<ul style = "text-align:center; display:inline-block; line-height:2em;">' +
          '<li style = "text-align:left">音を聴くことができるか，映像を見ることができるかの確認（所要時間：3分）</li>'+
          '<li style = "text-align:left">実験参加に対する同意</li>'+
          '<li style = "text-align:left">年齢・性別に関する質問（所要時間：約3分）</li>'+
          '<li style = "text-align:left">効果音に対する印象評価（約5分）</li>'+
          '<li style = "text-align:left">映像（音無し）に対する印象評価（約10分）</li>'+
          '<li style = "text-align:left">映像（音有り）に対する印象評価（約20分）</li>'+
          '<li style = "text-align:left">あなたの視覚的イメージ経験に関する調査（約10分）</li></ul>'+
          '<p>この時点で疑問がある方は正田悠（shoda（アット）people.kobe-u.ac.jp）に問い合わせてください。</p>'+
          '<p style = "text-align:center"><br> <b>問題ない方は「次へ」を押してください。</b></p></div>',
          
    button_label: '次へ'
    };
    
timeline.push(ic1);

///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
//音が聞こえますか？
var audiotest_inst = {
            type: 'html-button-response',
            stimulus: '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%; margin-left:10%;margin-right:10%;">'+
            '<h2><p>あなたの環境で音が鳴るかどうかの確認</h2></p><hr>'+
            '<p>この実験では音を聞く必要があります。あなたの環境で音を聞くことができるかを確認します。</p>'+
            '<p>「次へ」をクリックすると音楽が流れます。あなたのパソコンやスマートフォンの音量をもっとも小さい状態にしておいて，だんだんと大きくしていってください。<br>'+
            'もし音が聞こえない場合は，音量やイヤホン等をご確認ください。</p>'+
            '<p>あるいは使用するブラウザーを変更してみてください。<br>'+
            'Windowsの方はFirefox，Macの方はSafariを推奨します。<br>'+
            'Android端末の方はGoogle Chromeを，iOSの方は____というアプリをインストールして試してみてください。</p><br>'+
            '<p>それでも聞こえない場合には残念ながら実験に参加することができません。<br>'+
            '正田悠（shoda（アット）people.kobe-u.ac.jp）にお問い合わせください</p>'+
            '<hr><center>「開始」をクリックすると始まります。<br>音量に注意してください。</center></p><hr></div>',
            choices: ['開始'],
            timing_post_trial:500
            };
timeline.push(audiotest_inst);

var audiotest = {
            type: 'audio-button-response',
            stimulus: "https://shodalab.github.io/jsPsychSheet/experiment/sound/bgm.mp3",
            prompt: "<p>音が聞こえていたら「次へ」をクリックしてください。</p>",
            choices: ['次へ'],
            response_ends_trial: true,
            post_trial_gap:500
            };
timeline.push(audiotest);

///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
//映像OK？
var movietest_inst = {
            type: 'html-button-response',
            stimulus: '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%; margin-left:10%;margin-right:10%;">'+
            '<h2><p>あなたの環境で映像を見ることができるかどうかの確認</h2></p><hr>'+
            '<p>次に映像を見ることができるかを確認します。</p>'+
            '<p>この後，「次へ」をクリックすると映像が自動で流れます。<br>'+
            '映像を見ることができないあるいは音が聞こえない場合は，使用するブラウザーを変更してみてください。<br>'+
            'Windowsの方はFirefox，Macの方はSafariを推奨します。<br>'+
            'Android端末の方はGoogle Chromeを，iOSの方は____というアプリをインストールして試してみてください。</p><br>'+
            '<p>それでも映像を視聴できない場合には残念ながら実験に参加することができません。<br>'+
            '正田悠（shoda（アット）people.kobe-u.ac.jp）にお問い合わせください</p>'+
            '<hr><center>「開始」をクリックすると始まります。<br>音量に注意してください。</center></p><hr></div>',
            choices: ['開始'],
            timing_post_trial:500
            };
timeline.push(movietest_inst);

var movietest = {
            type: 'video-button-response',
            sources: ['https://shodalab.github.io/jsPsychSheet/experiment/video/sample_movie.mp4'],
            choices: ['次へ'],
            prompt: "<p>映像が流れるまで時間がかかることがあります。<br>映像を見ることができ，音が聞こえていたら「次へ」をクリックしてください。</p>",
            response_ends_trial: true,
            post_trial_gap:500,
            width:90
            }
timeline.push(movietest);
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
//説明文書と同意書
var ic2 = {
    type: 'survey-multi-select',
    questions: [{
        prompt: '<span style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%; margin-left:10%;margin-right:10%;"><b>以上の内容をよく読んで，理解した上で実験参加に同意いただける方はチェックをお願いします。同意されない方は，ウィンドウを閉じてください。</b></span>',
        options: ['<span style = "font-size: 14pt">&emsp; 説明事項をよく読み，理解した上で，研究参加に同意します。</span>'],
        required: true,
        name: 'approval'
    }],
    preamble: '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%; margin-left:10%;margin-right:10%;"><h2><p>実験の説明文書と実験参加に対する同意書</h2></p></div>'+
            '<div style = "font-size: 18px; line-height:1.8em; text-align: left; width: 80%;padding: 0% 5%;margin: 0% 5%;">' +
            '<h3>研究課題名：映像と効果音の印象評価実験</h3>' +
            'この実験に参加するかしないかはあなたの自由です。下記の説明文書を読んだ上で，実験に参加することに同意される場合は<b>このページ下部のチェックボックスにチェックを入れてください。</b></p>' +
            '<p><h3><b>1．研究の意義と目的</b></h3>' +
            '近年、動画編集・投稿はますます誰にでも身近なものになり、映像と音楽を組み合わせた作品作りも多く行われています。'+
            'この研究では、より良い映像作品作りの一助として、順再生及び逆再生映像とより調和する効果音について調べます。</p>' +
            '<p><h3><b>2．本研究の手続き</b></h3>' +
            'この研究では，心理学実験の参加を通して，あなたに関する5種類の情報を回答していただきます。<br>'+
            '&emsp;1) 年齢や性別といった一般的な情報<br>' +
            '&emsp;2) 短い効果音に関する印象評価<br>' +
            '&emsp;3) 短い映像（音無し）に関する印象評価<br>' +
            '&emsp;4) 短い映像（音有り）に関する印象評価<br>' +
            '&emsp;5) 視覚的イメージ経験に関する調査</p>' +
            '<p><h3><b>3．研究期間</b></h3>' +
            'この研究自体は2020年4月1日から2024年3月31日まで実施されますが，今回の実験は40分程度で終わるように作成されています。</p>' +
            '<p><h3><b>4．研究対象者の基準</b></h3>' +
            '&emsp;1) 選定基準と人数：18歳以上の大学生100人程度（男女ほぼ半数）の回答を予定しています。<br>' +
            '&emsp;2) 除外基準：上記の選定基準を満たす方であれば全員ご回答いただけます。</p>' +
            '<p><h3><b>5．研究に関する情報公開</b></h3>' +
            'この実験終了時に得られる内容については，希望される方にはお伝えすることができます。下記の問い合わせ先からご連絡ください。</p>' +
            '<p><h3><b>6．研究参加により起こりうる危険や不利益とそれらへの対処法</b></h3>' +
            'この実験において，参加者の心身を傷つけるような侵襲の危険性はありません。ただし，この実験に参加するかどうかはあなたの自由であり，あなたが実験を中止したいと思ったときにはいつでも参加をやめることができます。</p>'+
            '<p><h3><b>7．研究成果の公表</b></h3>' +
            'この実験で得られたデータは，個人情報の特定が不可能なように十分注意して，学会発表や論文として公表される可能性があります。 </p>' +
            '<p><h3><b>8．個人情報などの取り扱い，資料・情報の保管および破棄の方法</b></h3>' +
            'この実験でえられたデータは，研究担当者および研究代表者のみが使用します。収集したデータは研究期間が終了した5年後，すなわり2029年3月31日まで，鍵のかかるキャビネットあるいは情報漏れのないよう対策を施した'+
            'パソコンのハードディスクに保管します。その後，ハードディスク内のデータは消去します。</p>' +
            '<p><h3><b>9．この実験で得られた情報を将来の研究に用いる可能性</b></h3>' +
            'この実験で得られたデータおよび資料は，この研究を遂行するために必要な範囲においてのみ利用します。その後の別の研究で許可なく用いられることはありません。</p>' +
            '<p><h3><b>10．この実験にかかる費用</b></h3>' +
            'この実験にかかる費用については，神戸大学一般財源から支出されます。参加者の方に負担いただく費用は一切ありません。</p>' +
            '<p><h3><b>11．実験に対する問い合わせ</b></h3>' +
            '<p>神戸大学国際人間科学部グローバル文化学科&emsp;助教&emsp;正田悠（しょうだはるか）'+
            '<p>TEL:078-803-7423&emsp;&emsp;E-mail:shoda（アット）people.kobe-u.ac.jp'+
            '<p>住所：神戸市灘区鶴甲１−２−１</p><br><hr><br>',
    button_label: '次へ'
};


            
timeline.push(ic2);
//個人情報アンケート
            
var PersonalInfo_0 = {
            type: 'survey-html-form',
            preamble: '<div style = "font-size: 18px; line-height:1.8em; text-align: left; width: 80%;padding: 0% 5%;margin: 0% 5%;"><p><h2>あなた自身について１</h2></p></div><br>',
            html: 
            '<div style = "font-size: 18px; line-height:1.8em; text-align: left; width: 80%;padding: 0% 5%;margin: 0% 5%;">'+
            '<p style = "font-weight:bold">【学生の方のみ】あなたの学籍番号を記入してください。&emsp;<input name="studentID" type="text" /></p><br>'+
            '<p style = "font-weight:bold">性別をお答えください。</p>'+
            '<p>&emsp;男性 <input name="gender" type="radio" value ="男性" />&emsp;女性 <input name="sex" type="radio" value ="女性" />&emsp;それ以外<input name="gender" type="radio" value ="その他" /></p><br>'+
            '<p style = "font-weight:bold">あなたの年齢を記入してください。&emsp;<input name="age" type="text" />&emsp;歳</p><br>'+
            '<p style = "font-weight:bold">留学生の方は出身国を記入してください。&emsp;<input name="nationality" type="text" />&emsp;</p><br></div>',
            button_label: '次へ',
            };
timeline.push(PersonalInfo_0);

///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
//音量の調節
var volume_instruction = {
            type: 'html-button-response',
            stimulus: '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%; margin-left:10%;margin-right:10%;">'+
            '<h2><p>音量の調節</h2></p><hr>' +
            '<p>ここからはヘッドホンやスピーカーなど音を聞くための手段を用意してください。</p>'+
            '<p>この後，音を聴取する実験を始めますが，その前に音量のチェックを行っていただきます。<br><br>下の「開始」をクリックすると，音が3秒間聞こえてきます。<br>'+
            '<u>この音が小さすぎず大きすぎす，ちょうどよい音量になるように</u><br>ボリュームを調節してください。<br><br>'+
            'これを3回繰り返します。</p><br>'+
            '<hr><center>「開始」をクリックすると始まります。</center></p><hr></div>',
            choices: ['開始'],
            timing_post_trial:500
            };
timeline.push(volume_instruction);
            
var vol_stim = "https://shodalab.github.io/jsPsychSheet/experiment/sound/sound_check.mp3";
var repNum = ["1回目の調節終了", "2回目の調節終了", "3回目の調節終了"];
            
for (var i = 0; i < 3; i++){
      var choice_num = repNum[i];
      var trial_vol = {
            type: 'audio-button-response',
            stimulus: vol_stim,
            prompt: "<p><br>音量の調節が終了したら「調節終了」のボタンをクリックしてください。</p>",
            choices: [choice_num],
            response_ends_trial: true,
            post_trial_gap:500
            };
timeline.push(trial_vol);
            };

///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
var otonomi = {
timeline_variables: [
{sound1:'sound/increasing_sound.mp3'},
{sound1:'sound/decreasing_sound.mp3'}
],
timeline: [
    {type: 'audio-keyboard-response',
     stimulus: jsPsych.timelineVariable('sound1'),
     prompt: '<br><br>自動で次の画面に移ります',
     choices: jsPsych.NO_KEYS,
     trial_ends_after_audio: true,
     post_trial_gap:0
    },
    {type: 'survey-likert',
     questions: [
            {prompt: "<h3>以下の形容詞対のそれぞれついて，今聞いた音の印象を選んでください。<br>それぞれの形容詞対について７段階で評価してください。</h3><br>明るい―――暗い", name: '暗い', labels: ["&#8592;明るい","","","どちらでも<br>ない","","","暗い&#8594;"], required: true},
            {prompt: "静かな―――動的な", name: '動的な', labels: ["&#8592;静かな","","","どちらでも<br>ない","","","動的な&#8594;"], required: true},
            {prompt: "印象深い―――印象がうすい", name: '印象がうすい', labels: ["&#8592;印象深い","","","どちらでも<br>ない","","","印象がうすい&#8594;"], required: true},
            {prompt: "ありふれた―――ユニークな", name: 'ユニークな', labels: ["&#8592;ありふれた","","","どちらでも<br>ない","","","ユニークな&#8594;"], required: true},
            {prompt: "派手な―――地味な", name: '地味な', labels: ["&#8592;派手な","","","どちらでも<br>ない","","","地味な&#8594;"], required: true},
            {prompt: "ぼけた―――鮮やかな", name: '鮮やかな', labels: ["&#8592;ぼけた","","","どちらでも<br>ない","","","鮮やかな&#8594;"], required: true},
            {prompt: "白熱した―――淡々とした", name: '淡々とした', labels: ["&#8592;白熱した","","","どちらでも<br>ない","","","淡々とした&#8594;"], required: true},
            {prompt: "不思議でない―――不思議な", name: '不思議な', labels: ["&#8592;不思議でない","","","どちらでも<br>ない","","","不思議な&#8594;"], required: true},
            {prompt: "面白い―――面白くない", name: '面白くない', labels: ["&#8592;面白い","","","どちらでも<br>ない","","","面白くない&#8594;"], required: true},
            {prompt: "明快な―――ぼんやりした", name: 'ぼんやりした', labels: ["&#8592;明快な","","","どちらでも<br>ない","","","ぼんやりした&#8594;"], required: true},
            {prompt: "幻想的な―――リアルな", name: 'リアルな', labels: ["&#8592;幻想的な","","","どちらでも<br>ない","","","リアルな&#8594;"], required: true},
            {prompt: "好きな―――嫌いな", name: '嫌いな', labels: ["&#8592;好きな","","","どちらでも<br>ない","","","嫌いな&#8594;"], required: true},
            ],
     require_movement: true,
     button_label: '次へ',
     post_trial_gap:500
     }],

repetitions: 1,
randomize_order: true
};
           
timeline.push(otonomi);  
///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
//映像のみの評価
            var videoonly_pr_inst_2 = {
            type: 'html-button-response',
            stimulus: '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%;padding: 0% 2.5%;margin: 0% 2.5%;">'+
            '<h2><p>映像の評価（音なし）</h2></p></div>' +
            '<div style = "font-size: 18px; line-height:1.8em; text-align: center; width: 80%;padding: 0% 2.5%;margin: 0% 2.5%;"><p>' +
            '次は音ではなく，短い映像を見ていただきます。映像が流れているときにはマウスのクリックや画面のタッチを行わないでください。</p>'+
            '<p>短い映像ですので見逃さないように注意してください。このとき，音は流れません。</p>'+
            '<p>映像には，普通に流れるもの（順再生）と，逆回しで流れるもの（逆再生）があります。</p>'+
            '<p>その後，印象を尋ねるアンケートが表れますので，すべての項目に回答してください。</p>' +
            '<p>まずは練習を行います。練習は2回行います。</p>' +
            '<hr><p><b>「開始」をクリックすると始まります。</b><hr></p></div>',
            choices: ['開始'],
            post_trial_gap:500
            };
            timeline.push(videoonly_pr_inst_2);
            
var trial_procedure2 = {
timeline: [
    {
            type: 'video-keyboard-response',
            sources: jsPsych.timelineVariable('sources1'),
            choices: jsPsych.NO_KEYS,
            margin_vertical: '10px',
            margin_horizontal: '8px',
            prompt: '<br><br>再生まで時間がかかる場合があります。<br>自動で次の画面に移ります',
            width: 600,
            //height: 600,
            autoplay: true,
            //controls: true,
            //start: 8,
            //stop: 9,
            //rate: 1.5,
            //trial_duration: 3000,
            trial_ends_after_video: true,
            post_trial_gap:500
    },
{
            type: 'survey-likert',
            questions: [
            {prompt: "<h3>以下の形容詞対のそれぞれついて，今みた映像の印象を選んでください。<br>それぞれの形容詞対について７段階で評価してください。</h3><br>順再生らしい―――逆再生らしい", name: '逆再生らしい', labels: ["&#8592;<br>順再生<br>らしい","","","どちらでも<br>ない","","","&#8594;<br>逆再生<br>らしい"], required: true},
            {prompt: "明るい―――暗い", name: '暗い', labels: ["&#8592;明るい","","","どちらでも<br>ない","","","暗い&#8594;"], required: true},
                {prompt: "静かな―――動的な", name: '動的な', labels: ["&#8592;静かな","","","どちらでも<br>ない","","","動的な&#8594;"], required: true},
            {prompt: "印象深い―――印象がうすい", name: '印象がうすい', labels: ["&#8592;印象深い","","","どちらでも<br>ない","","","印象がうすい&#8594;"], required: true},
            {prompt: "ありふれた―――ユニークな", name: 'ユニークな', labels: ["&#8592;ありふれた","","","どちらでも<br>ない","","","ユニークな&#8594;"], required: true},
            {prompt: "派手な―――地味な", name: '地味な', labels: ["&#8592;派手な","","","どちらでも<br>ない","","","地味な&#8594;"], required: true},
            {prompt: "ぼけた―――鮮やかな", name: '鮮やかな', labels: ["&#8592;ぼけた","","","どちらでも<br>ない","","","鮮やかな&#8594;"], required: true},
            {prompt: "白熱した―――淡々とした", name: '淡々とした', labels: ["&#8592;白熱した","","","どちらでも<br>ない","","","淡々とした&#8594;"], required: true},
            {prompt: "不思議でない―――不思議な", name: '不思議な', labels: ["&#8592;不思議でない","","","どちらでも<br>ない","","","不思議な&#8594;"], required: true},
            {prompt: "面白い―――面白くない", name: '面白くない', labels: ["&#8592;面白い","","","どちらでも<br>ない","","","面白くない&#8594;"], required: true},
            {prompt: "明快な―――ぼんやりした", name: 'ぼんやりした', labels: ["&#8592;明快な","","","どちらでも<br>ない","","","ぼんやりした&#8594;"], required: true},
            {prompt: "幻想的な―――リアルな", name: 'リアルな', labels: ["&#8592;幻想的な","","","どちらでも<br>ない","","","リアルな&#8594;"], required: true},
            {prompt: "好きな―――嫌いな", name: '嫌いな', labels: ["&#8592;好きな","","","どちらでも<br>ない","","","嫌いな&#8594;"], required: true},],
            //scale_width:1000,
            require_movement: true,
            button_label: '次へ',
            post_trial_gap:500
            }
],
timeline_variables: [
  { sources1: ['https://shodalab.github.io/jsPsychSheet/experiment/video/pr1.mp4']},
  { sources1: ['https://shodalab.github.io/jsPsychSheet/experiment/video/pr2.mp4']},
],
repetitions: 1,
randomize_order: true
};
           
       
timeline.push(trial_procedure2);               

          
           

///////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////
var audio = [
    'https://shodalab.github.io/jsPsychSheet/experiment/sound/bgm.mp3', 
    'https://shodalab.github.io/jsPsychSheet/experiment/sound/decreasing_sound.mp3', 
    'https://shodalab.github.io/jsPsychSheet/experiment/sound/increasing_sound.mp3', 
    'https://shodalab.github.io/jsPsychSheet/experiment/sound/sound_check.mp3'    
    ];

jsPsych.init({
    timeline: timeline,
    preload_audio: audio,
    use_webaudio: false,
    on_finish: function() {
     jsPsychSheet.uploadData(jsPsych.data.get().csv());;
    }
});
```
